name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - conda=4.7.11
  - conda-env=2.6.0
  - conda-package-handling=1.3.11
  - cryptography=2.7
  - idna=2.8
  - libarchive=3.3.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=8.2.0
  - libxml2=2.9.9
  - lz4-c=1.8.1.2
  - lzo=2.10
  - ncurses=6.1
  - openssl=1.1.1c
  - pip=19.2.2
  - pycosat=0.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.0
  - python=3.7.4
  - python-libarchive-c=2.8
  - readline=7.0
  - requests=2.22.0
  - ruamel_yaml=0.15.46
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - urllib3=1.24.2
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - attrs==19.1.0
    - beautifulsoup4==4.8.0
    - bert==2.2.0
    - blis==0.2.4
    - bottleneck==1.2.1
    - cycler==0.10.0
    - cymem==2.0.2
    - erlastic==2.0.0
    - fastai==1.0.57
    - fastprogress==0.1.21
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - murmurhash==1.0.2
    - numexpr==2.7.0
    - numpy==1.17.0
    - nvidia-ml-py3==7.352.0
    - packaging==19.1
    - pandas==0.25.0
    - pillow==6.1.0
    - plac==0.9.6
    - preshed==2.0.1
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pytz==2019.2
    - pyyaml==5.1.2
    - scipy==1.3.1
    - soupsieve==1.9.3
    - spacy==2.1.8
    - srsly==0.1.0
    - thinc==7.0.8
    - torch==1.2.0
    - torchvision==0.4.0
    - tqdm==4.34.0
    - wasabi==0.2.2

