name: mura
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.5.0
  - jupyterlab=1.0.2
  - jupyterlab_server=1.0.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - torchvision=0.4.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.8.0
    - autopep8==1.4.4
    - flake8==3.7.8
    - grpcio==1.23.0
    - markdown==3.1.1
    - mccabe==0.6.1
    - pep8==1.7.1
    - protobuf==3.9.1
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - tensorboard==1.14.0
    - tensorboardx==1.8
    - torchsummary==1.5.1
    - werkzeug==0.15.5
    - Flask==1.1.1
    - Flask-Cors==3.0.8

